### ISSUE TITLE
Searching edge in named graphs

### ISSUE THREAD

**Issue by xmethos** [Riduidel/gaedo#44]
`GraphUtils::IsInNamedGraph` should return true for a given edge when it is one of the named graphs given as arguments, and **not** only when edge has all named graphs.

**Comment by Riduidel** [comment]
Can you please provide some documentation reference explaining why this should be the case ? (I will make that change, no problem, but I want to be sure this behaviour correspond, in one sense or another, to an existing established standard, or a rule of thumb, or any prior art that would reveal we don't do a mistake here)

**Comment by alexblanquart** [comment]
It is already possible in blueprints to search for statements in a collection of contexts : [`GraphSailConnection#getStatemensInternal`](http://www.tinkerpop.com/maven2/com/tinkerpop/blueprints/blueprints/1.2/api/com/tinkerpop/blueprints/pgm/oupls/sail/GraphSailConnection.html). In this implementation, the statements may not be in all specified contexts but only in a subset, which the `GraphUtils#isInNamedGraph` implementation does not permit.
