### ISSUE TITLE
Indexes not updated on node deletion

### ISSUE THREAD

**Issue by Kricket** [Riduidel/gaedo#58]
I have two different enum classes, but each has a value LEFT.
If I try to delete both of them, the second fails with a neo4j error:

java.lang.IllegalStateException: Node[2344] has been deleted in this tx

This appears to be because the indexes are not updated when a node is removed in GraphUtils#removeSafely.

**Comment by Riduidel** [comment]
There is surely a link between this one and #56

**Comment by Riduidel** [comment]
Should be fixed by 30ebfda
