### ISSUE TITLE
"edges" index is taking too much space in database

### ISSUE THREAD

**Issue by alexblanquart** [Riduidel/gaedo#59]
Is it possible to tell Gaedo not to use anymore this index, as it takes lots of space and does not seem relevant anymore in current implementation ?

**Comment by alexblanquart** [comment]
As an example, in a 30Go neo4j database we can get back 10Go just by dropping this index, and the application still works with a slight adaptation of `IndexableGraphBackedFinderService`, which does not store anything and use this index.

**Comment by Riduidel** [comment]
Modification list in `IndexableGraphBackedFinderService`
- don't create the edge index in the loadIndices method
- remove `EDGES` from `IndexNames` enum (or at least mark it as not usable) and change the way these indices should be grabbed
- In `createEdgeFor`, no more add edge to `EDGES` index
- In `setIndexedProperty`, make sure `EDGES`is handled correctly.
