### ISSUE TITLE
Possible optimization in loadVertex method

### ISSUE THREAD

**Issue by alexblanquart** [Riduidel/gaedo#71]
`IndexableGraphBackedFinderService#loadVertexFor(String, String)` method uses graph index. Thus, as it is called many times during all kind of operations, this increases the actual time of each operation.

Would it be possible to rely less on the index ? Would it be possible to use the index only to get the starting vertex and then rely only on graph traversals ?

**Comment by Riduidel** [comment]
In fact, it would bee nice to use a "local" graph driver that would first explore the subgraph linked to initial vertex before to call those indices.

Typically, during update operation, we can assume most of the fields aren't modified and, as a consequence, their associated vertices won't change. In such a case, it would be a huge improvement to generate a local cache before to rely upon neo4j index ...
