### ISSUE TITLE
Deletion of map entry not done enterily

### ISSUE THREAD

**Issue by alexblanquart** [Riduidel/gaedo#91]
It appears that `AbstractBluePrintsBackedFinderService#deleteOutEdgeVertex(...)` does not cascade the deletion of a map entry on contrary to other classes present in the service repository.

**Comment by Riduidel** [comment]
Seems like it is due to the fact Ma$Entry classes are tuples, which specific case is not handled during delete operations as well as it is during create or update ones.

A good test should be able to expose that easily ...

**Comment by Riduidel** [comment]
Interesting : issue is not only that `deleteOutEdgeVertex` does nothing. it's also that, if map data was stored in graph at obejct creation, the synthetic id used for `Map.Entry` don't contain the object id.

In other words, it seems gaedo create the `Map.Entry` vertex before even assigning an id to map entry key or value. This is just plain wrong.

Look, it's just there, in `AbstractTupleTransformer#getVertexFor(...)` :

```
    // First step is to build an id for given tuple by concatenating key and value id (which is hopefully done separately)
    String entryVertexId = getIdOfTuple(service.getRepository(), cast, cascade, objectsBeingUpdated);
```

As that `entryVertexId` is never recomputed, the value may not have yet its own id created, which imply tuple id will be awfully bad.
